apiVersion: v2
name: test-chart
description: A Helm chart for Kubernetes

type: application

# This is the chart version.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "1.0.0" # https://access.redhat.com/support/policy/updates/openshift # paragraph "OpenShift Support Matrix"
