apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  annotations:
    basevalue: {{ .Values.basevalue }}
    extravalue: {{ .Values.extravalue }}
    overridevalue: {{ .Values.overridevalue }}

  {{- with .Values.listvalue }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- range $key, $value := .Values.objectvalue }}
    key: "{{ $key }}"
    keyvalue: "{{ $value }}"
  {{- end }}

